package enrichment

// defaultAirlines is the built-in airline lookup table.
// Keyed by ICAO callsign prefix (e.g. "SWA" for Southwest).
var defaultAirlines = map[string]*AirlineInfo{
	"AAL": {Name: "American Airlines", ICAO: "AAL", Country: "United States"},
	"AAR": {Name: "Asiana Airlines", ICAO: "AAR", Country: "South Korea"},
	"ACA": {Name: "Air Canada", ICAO: "ACA", Country: "Canada"},
	"AFR": {Name: "Air France", ICAO: "AFR", Country: "France"},
	"AIC": {Name: "Air India", ICAO: "AIC", Country: "India"},
	"AMX": {Name: "Aeromexico", ICAO: "AMX", Country: "Mexico"},
	"ANA": {Name: "All Nippon Airways", ICAO: "ANA", Country: "Japan"},
	"ANZ": {Name: "Air New Zealand", ICAO: "ANZ", Country: "New Zealand"},
	"ASA": {Name: "Alaska Airlines", ICAO: "ASA", Country: "United States"},
	"AVA": {Name: "Avianca", ICAO: "AVA", Country: "Colombia"},
	"AZA": {Name: "ITA Airways", ICAO: "AZA", Country: "Italy"},
	"BAW": {Name: "British Airways", ICAO: "BAW", Country: "United Kingdom"},
	"CCA": {Name: "Air China", ICAO: "CCA", Country: "China"},
	"CES": {Name: "China Eastern Airlines", ICAO: "CES", Country: "China"},
	"CKS": {Name: "Kalitta Air", ICAO: "CKS", Country: "United States"},
	"CPA": {Name: "Cathay Pacific", ICAO: "CPA", Country: "Hong Kong"},
	"CSC": {Name: "Sichuan Airlines", ICAO: "CSC", Country: "China"},
	"CSN": {Name: "China Southern Airlines", ICAO: "CSN", Country: "China"},
	"DAL": {Name: "Delta Air Lines", ICAO: "DAL", Country: "United States"},
	"DLH": {Name: "Lufthansa", ICAO: "DLH", Country: "Germany"},
	"EDV": {Name: "Endeavor Air", ICAO: "EDV", Country: "United States"},
	"EIN": {Name: "Aer Lingus", ICAO: "EIN", Country: "Ireland"},
	"EJA": {Name: "NetJets", ICAO: "EJA", Country: "United States"},
	"EJM": {Name: "Executive Jet Management", ICAO: "EJM", Country: "United States"},
	"ENY": {Name: "Envoy Air", ICAO: "ENY", Country: "United States"},
	"ETH": {Name: "Ethiopian Airlines", ICAO: "ETH", Country: "Ethiopia"},
	"EVA": {Name: "EVA Air", ICAO: "EVA", Country: "Taiwan"},
	"EVAC": {Name: "US Air Force", ICAO: "EVAC", Country: "United States"},
	"EWG": {Name: "Eurowings", ICAO: "EWG", Country: "Germany"},
	"FDX": {Name: "FedEx Express", ICAO: "FDX", Country: "United States"},
	"FFT": {Name: "Frontier Airlines", ICAO: "FFT", Country: "United States"},
	"FIN": {Name: "Finnair", ICAO: "FIN", Country: "Finland"},
	"GEC": {Name: "Lufthansa Cargo", ICAO: "GEC", Country: "Germany"},
	"GTI": {Name: "Atlas Air", ICAO: "GTI", Country: "United States"},
	"HAL": {Name: "Hawaiian Airlines", ICAO: "HAL", Country: "United States"},
	"IBE": {Name: "Iberia", ICAO: "IBE", Country: "Spain"},
	"ICE": {Name: "Icelandair", ICAO: "ICE", Country: "Iceland"},
	"JAL": {Name: "Japan Airlines", ICAO: "JAL", Country: "Japan"},
	"JBU": {Name: "JetBlue Airways", ICAO: "JBU", Country: "United States"},
	"JIA": {Name: "PSA Airlines", ICAO: "JIA", Country: "United States"},
	"JSX": {Name: "JSX", ICAO: "JSX", Country: "United States"},
	"JTL": {Name: "Jet Linx", ICAO: "JTL", Country: "United States"},
	"KAL": {Name: "Korean Air", ICAO: "KAL", Country: "South Korea"},
	"KLM": {Name: "KLM Royal Dutch Airlines", ICAO: "KLM", Country: "Netherlands"},
	"LNI": {Name: "Lion Air", ICAO: "LNI", Country: "Indonesia"},
	"LOT": {Name: "LOT Polish Airlines", ICAO: "LOT", Country: "Poland"},
	"NKS": {Name: "Spirit Airlines", ICAO: "NKS", Country: "United States"},
	"PAC": {Name: "Polar Air Cargo", ICAO: "PAC", Country: "United States"},
	"QFA": {Name: "Qantas", ICAO: "QFA", Country: "Australia"},
	"QTR": {Name: "Qatar Airways", ICAO: "QTR", Country: "Qatar"},
	"RPA": {Name: "Republic Airways", ICAO: "RPA", Country: "United States"},
	"RYR": {Name: "Ryanair", ICAO: "RYR", Country: "Ireland"},
	"SAS": {Name: "Scandinavian Airlines", ICAO: "SAS", Country: "Sweden"},
	"SCX": {Name: "Sun Country Airlines", ICAO: "SCX", Country: "United States"},
	"SIA": {Name: "Singapore Airlines", ICAO: "SIA", Country: "Singapore"},
	"SKW": {Name: "SkyWest Airlines", ICAO: "SKW", Country: "United States"},
	"SWA": {Name: "Southwest Airlines", ICAO: "SWA", Country: "United States"},
	"SWR": {Name: "Swiss International Air Lines", ICAO: "SWR", Country: "Switzerland"},
	"TAP": {Name: "TAP Air Portugal", ICAO: "TAP", Country: "Portugal"},
	"THA": {Name: "Thai Airways", ICAO: "THA", Country: "Thailand"},
	"THY": {Name: "Turkish Airlines", ICAO: "THY", Country: "Turkey"},
	"UAL": {Name: "United Airlines", ICAO: "UAL", Country: "United States"},
	"UAE": {Name: "Emirates", ICAO: "UAE", Country: "United Arab Emirates"},
	"UPS": {Name: "UPS Airlines", ICAO: "UPS", Country: "United States"},
	"VIR": {Name: "Virgin Atlantic", ICAO: "VIR", Country: "United Kingdom"},
	"VOI": {Name: "Volaris", ICAO: "VOI", Country: "Mexico"},
	"VRD": {Name: "Virgin America", ICAO: "VRD", Country: "United States"},
	"WJA": {Name: "WestJet", ICAO: "WJA", Country: "Canada"},
}
